---
user_info:
  email: 'TODO'
  name: 'TODO'
configure_git_global_settings: False
ssh:
  generate_ssh_key: False
  ssh_key_path: ed25519
  sshd_enabled: False
config_files:
  all:
    - name: tmux
      src: config-files/tmux.conf
      dst: $HOME/.tmux.conf
    - name: vim
      src: config-files/vimrc
      dst: $HOME/.vimrc
  personal:
    - name: nethack
      src: config-files/nethackrc
      dst: $HOME/.nethackrc
  work:
applications:
  all:
    - docker
    - git
    - the_silver_searcher
    - tmux
    - vim
  personal:
    - nethack
    - openssh
    - veracrypt
  work:
macos:
  applications:
    all:
      brew:
        casks:
          - google-chrome
          - firefox
          - gimp
          - inkscape
          - iterm2
          - slack
          - visual-studio-code
          - zoom
    personal:
    work:
manjaro_linux:
  applications:
    all:
      - gimp
      - inkscape
    snap_applications:
      - "code --classic"
      - "slack --classic"
