FROM alpine:3.14

COPY ./requirements.txt .

RUN apk add py3-pip && \
    pip3 install -r requirements.txt

WORKDIR /config
# COPY ./config-files ./config-files
# COPY ./lib ./lib
# COPY ./platforms ./platforms
# COPY ./test/config.yml .
# COPY ./*.py .

COPY ./ .
COPY ./test/config.yml ./config.yml
