#!/bin/sh

export PATH=$PATH:$HOME/scripts:./

case "$SHELL" in
  *bash*) export PS1='\033[01;32m\]\W\033[00m\]\$ ' ;;
  *zsh*) export PROMPT="%F{#A149C9}%m:%F{#63C936}%~%# %F{FFF}" ;;
esac

alias glog="git log --pretty=format:'%C(yellow)%h %Cred%ad %Cblue%an%Cgreen%d %Creset%s' --date=short"
alias grep='grep --color=auto'
alias guf='git checkout master && git pull --rebase && git checkout -'
alias ls='ls -G --color'
alias tmc='tmux clear-history'
alias vi=vim
